version: "1"
services:
  consumer:
    container_name: consumer
    build: ./consumer
    ports: 
      - 4002:4002
    volumes: 
      - ./consumer:/app
    restart: always
    entrypoint: ["nodemon", "-L", "/app/index.js"]  
    depends_on: 
      rabb: 
        condition: service_healthy    
    networks:
      - em
  producer:
    container_name: producer
    build: ./producer
    ports: 
      - 4001:4001
    volumes: 
      - ./producer:/app
    networks:
      - em      
    restart: always
    entrypoint: ["nodemon", "-L", "/app/index.js"]  
    depends_on: 
      rabb:
       condition: service_healthy

  rabb:
    image: rabbitmq
    container_name: rabb
    restart: on-failure
    ports: 
      - 5672:5672
    networks:
      - em
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3  

networks:
  em:
    driver: bridge

